tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Official Amazon AWS command-line interface
brew "awscli"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima", restart_service: true
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# CLI for interacting with Doppler secrets and configuration
brew "doppler"
# Modern, maintained replacement for ls
brew "eza"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Task is a task runner/build tool that aims to be simpler and easier to use
brew "go-task"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit", args: ["build-from-source"]
# Mac App Store command-line interface
brew "mas"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Python version management
brew "pyenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# OpenTofu / Terraform / Terragrunt / Atmos version manager
brew "tenv"
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Linter for Terraform files
brew "tflint"
# Static analysis security scanner for your terraform code
brew "tfsec"
# Terminal multiplexer
brew "tmux"
# JavaScript toolchain manager for reproducible environments
brew "volta"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# GPU-accelerated terminal emulator
cask "alacritty"
# Application launcher and productivity software
cask "alfred"
# Chromium based browser
cask "arc"
# Desktop password and login vault
cask "bitwarden"
# Voice and text chat software
cask "discord"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Open-source code editor
cask "visual-studio-code"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
# Native desktop client for WhatsApp
cask "whatsapp"
# Video communication and virtual meeting platform
cask "zoom"
mas "LastPass", id: 926036361
vscode "a-h.templ"
vscode "astro-build.astro-vscode"
vscode "ckolkman.vscode-postgres"
vscode "dracula-theme.theme-dracula"
vscode "editorconfig.editorconfig"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.makefile-tools"
vscode "pkief.material-icon-theme"
vscode "tamasfe.even-better-toml"
