[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "…/"

[git_status]
disabled = true

# [time]
# disabled = false
# time_format = "%Y-%m-%d %H:%M"
# utc_time_offset = "local"

[python]
pyenv_version_name = true
