---
- name: ensure docker-compose installed
  homebrew:
    name: docker-compose
    state: present

- name: ensure docker plugins directory exists
  file:
    path: "~/.docker/cli-plugins"
    state: directory

- name: link compose executable to docker plugin directory
  file:
    src: "{{ brew_prefix.stdout }}/opt/docker-compose/bin/docker-compose"
    dest: "~/.docker/cli-plugins/docker-compose"
    state: link
