---
- name: ensure .ssh directory exists.
  file:
    dest: "{{ home_env }}/.ssh/"
    mode: 0700
    state: directory

- name: install ssh secret key
  copy:
    src: "{{ dotfiles_secrets }}/ssh/id_ed25519"
    dest: "{{ home_env }}/.ssh/id_ed25519"
    mode: 0600

- name: install ssh public key
  copy:
    src: "{{ dotfiles_secrets }}/ssh/id_ed25519.pub"
    dest: "{{ home_env }}/.ssh/id_ed25519.pub"
    mode: 0644

- name: start ssh-agent and add private key
  shell: |
      eval "$(ssh-agent)"
      ssh-add {{ home_env }}/.ssh/id_ed25519
  changed_when: false  # return ok

# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ ansible_facts.user_id }}"
#     state: present
#     key: "~/.ssh/id_ed25519"
