- stow:
    state: present
    package: '{{ item }}'
    dir: '{{ dotfiles_home }}'
  with_items:
    - alacritty
    - git
    - homebrew
    - jq
    - ssh
    - starship
    - zsh

- stow:
    state: present
    package: vscode
    dir: '{{ dotfiles_home }}/vscode/mine'
    target: '"$HOME/Library/Application Support/Code/User/"'
