---
- hosts: localhost

  vars:
    home_env: "{{ lookup('env', 'HOME') }}"
    dotfiles_home: "{{ home_env }}/.dotfiles"
    dotfiles_secrets: "{{ dotfiles_home }}/.secrets"

  pre_tasks:
    - name : set brew prefix
      shell: echo $(brew --prefix)
      register: brew_prefix
      changed_when: false  # return ok
      tags: [ always ]

  tasks:

    - import_tasks: tasks/stow.yml
      tags: stow

    - import_tasks: tasks/zsh.yml
      tags: zsh

    # - import_tasks: tasks/ssh.yml
    #   tags: ssh
      
    - import_tasks: tasks/docker.yml
      tags: docker
      
    - import_tasks: tasks/dbt.yml
      tags: dbt
      
    - import_tasks: tasks/node.yml
      tags: node
